eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY:false}

server.port=${SERVER_PORT:8761}
