spring.application.name=api-gateway
server.port=8083
server.address=0.0.0.0
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

# auth-service
spring.cloud.gateway.routes[0].id=auth-service-login
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/login
spring.cloud.gateway.routes[0].predicates[1]=Method=POST

spring.cloud.gateway.routes[1].id=auth-service-register
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/register
spring.cloud.gateway.routes[1].predicates[1]=Method=POST

spring.cloud.gateway.routes[2].id=auth-service-test
spring.cloud.gateway.routes[2].uri=lb://auth-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/test
spring.cloud.gateway.routes[2].predicates[1]=Method=GET

spring.cloud.gateway.routes[3].id=auth-service-change-password
spring.cloud.gateway.routes[3].uri=lb://auth-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/auth/password/{id}
spring.cloud.gateway.routes[3].predicates[1]=Method=PUT

spring.cloud.gateway.routes[4].id=auth-service-delete-account
spring.cloud.gateway.routes[4].uri=lb://auth-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auth/{id}
spring.cloud.gateway.routes[4].predicates[1]=Method=DELETE

spring.cloud.gateway.routes[5].id=auth-service-token-validate
spring.cloud.gateway.routes[5].uri=lb://auth-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/token/validate
spring.cloud.gateway.routes[5].predicates[1]=Method=GET

spring.cloud.gateway.routes[6].id=auth-service-token-user-info
spring.cloud.gateway.routes[6].uri=lb://auth-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/token/user-info
spring.cloud.gateway.routes[6].predicates[1]=Method=GET

# user-service
spring.cloud.gateway.routes[7].id=user-service-get
spring.cloud.gateway.routes[7].uri=lb://user-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/users/{id}
spring.cloud.gateway.routes[7].predicates[1]=Method=GET

spring.cloud.gateway.routes[8].id=user-service-create
spring.cloud.gateway.routes[8].uri=lb://user-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/users/create
spring.cloud.gateway.routes[8].predicates[1]=Method=POST

spring.cloud.gateway.routes[9].id=user-service-update
spring.cloud.gateway.routes[9].uri=lb://user-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/users/{id}
spring.cloud.gateway.routes[9].predicates[1]=Method=PUT

spring.cloud.gateway.routes[10].id=user-service-delete
spring.cloud.gateway.routes[10].uri=lb://user-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/users/{id}
spring.cloud.gateway.routes[10].predicates[1]=Method=DELETE

# social-service
spring.cloud.gateway.routes[11].id=social-service-send-friend-request
spring.cloud.gateway.routes[11].uri=lb://social-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/friendRequests/
spring.cloud.gateway.routes[11].predicates[1]=Method=POST

spring.cloud.gateway.routes[12].id=social-service-accept-friend-request
spring.cloud.gateway.routes[12].uri=lb://social-service
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/friendRequests/{id}/accept
spring.cloud.gateway.routes[12].predicates[1]=Method=PUT

spring.cloud.gateway.routes[13].id=social-service-reject-friend-request
spring.cloud.gateway.routes[13].uri=lb://social-service
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/friendRequests/{id}/reject
spring.cloud.gateway.routes[13].predicates[1]=Method=PUT

spring.cloud.gateway.routes[14].id=social-service-get-received
spring.cloud.gateway.routes[14].uri=lb://social-service
spring.cloud.gateway.routes[14].predicates[0]=Path=/api/friendRequests/received/{receiverId}
spring.cloud.gateway.routes[14].predicates[1]=Method=GET

spring.cloud.gateway.routes[15].id=social-service-get-sent
spring.cloud.gateway.routes[15].uri=lb://social-service
spring.cloud.gateway.routes[15].predicates[0]=Path=/api/friendRequests/sent/{senderId}
spring.cloud.gateway.routes[15].predicates[1]=Method=GET

spring.cloud.gateway.routes[16].id=social-service-get-approved
spring.cloud.gateway.routes[16].uri=lb://social-service
spring.cloud.gateway.routes[16].predicates[0]=Path=/api/friendRequests/approved/{userId}
spring.cloud.gateway.routes[16].predicates[1]=Method=GET

spring.cloud.gateway.routes[17].id=social-service-get-sent-pending
spring.cloud.gateway.routes[17].uri=lb://social-service
spring.cloud.gateway.routes[17].predicates[0]=Path=/api/friendRequests/sent/pending/{senderId}
spring.cloud.gateway.routes[17].predicates[1]=Method=GET

spring.cloud.gateway.routes[18].id=social-service-get-received-pending
spring.cloud.gateway.routes[18].uri=lb://social-service
spring.cloud.gateway.routes[18].predicates[0]=Path=/api/friendRequests/received/pending/{receiverId}
spring.cloud.gateway.routes[18].predicates[1]=Method=GET

# workout-service workouts
spring.cloud.gateway.routes[19].id=workout-service-create-workout
spring.cloud.gateway.routes[19].uri=lb://workout-service
spring.cloud.gateway.routes[19].predicates[0]=Path=/api/workouts,/api/workouts/
spring.cloud.gateway.routes[19].predicates[1]=Method=POST

spring.cloud.gateway.routes[20].id=workout-service-get-workout
spring.cloud.gateway.routes[20].uri=lb://workout-service
spring.cloud.gateway.routes[20].predicates[0]=Path=/api/workouts/{id}
spring.cloud.gateway.routes[20].predicates[1]=Method=GET

spring.cloud.gateway.routes[21].id=workout-service-get-user-workouts
spring.cloud.gateway.routes[21].uri=lb://workout-service
spring.cloud.gateway.routes[21].predicates[0]=Path=/api/workouts/user/{userId}
spring.cloud.gateway.routes[21].predicates[1]=Method=GET

spring.cloud.gateway.routes[22].id=workout-service-update-workout
spring.cloud.gateway.routes[22].uri=lb://workout-service
spring.cloud.gateway.routes[22].predicates[0]=Path=/api/workouts/{id}
spring.cloud.gateway.routes[22].predicates[1]=Method=PUT

spring.cloud.gateway.routes[23].id=workout-service-delete-workout
spring.cloud.gateway.routes[23].uri=lb://workout-service
spring.cloud.gateway.routes[23].predicates[0]=Path=/api/workouts/{id}
spring.cloud.gateway.routes[23].predicates[1]=Method=DELETE

# workout-service training programs
spring.cloud.gateway.routes[24].id=workout-service-create-program
spring.cloud.gateway.routes[24].uri=lb://workout-service
spring.cloud.gateway.routes[24].predicates[0]=Path=/api/training-programs,/api/training-programs/
spring.cloud.gateway.routes[24].predicates[1]=Method=POST

spring.cloud.gateway.routes[25].id=workout-service-get-program
spring.cloud.gateway.routes[25].uri=lb://workout-service
spring.cloud.gateway.routes[25].predicates[0]=Path=/api/training-programs/{id}
spring.cloud.gateway.routes[25].predicates[1]=Method=GET

spring.cloud.gateway.routes[26].id=workout-service-get-user-programs
spring.cloud.gateway.routes[26].uri=lb://workout-service
spring.cloud.gateway.routes[26].predicates[0]=Path=/api/training-programs/user/{userId}
spring.cloud.gateway.routes[26].predicates[1]=Method=GET

spring.cloud.gateway.routes[27].id=workout-service-update-program
spring.cloud.gateway.routes[27].uri=lb://workout-service
spring.cloud.gateway.routes[27].predicates[0]=Path=/api/training-programs/{id}
spring.cloud.gateway.routes[27].predicates[1]=Method=PUT

spring.cloud.gateway.routes[28].id=workout-service-delete-program
spring.cloud.gateway.routes[28].uri=lb://workout-service
spring.cloud.gateway.routes[28].predicates[0]=Path=/api/training-programs/{id}
spring.cloud.gateway.routes[28].predicates[1]=Method=DELETE

# workout-service exercises
spring.cloud.gateway.routes[29].id=workout-service-get-exercises
spring.cloud.gateway.routes[29].uri=lb://workout-service
spring.cloud.gateway.routes[29].predicates[0]=Path=/api/exercises,/api/exercises/
spring.cloud.gateway.routes[29].predicates[1]=Method=GET

spring.cloud.gateway.routes[30].id=workout-service-get-exercise-by-id
spring.cloud.gateway.routes[30].uri=lb://workout-service
spring.cloud.gateway.routes[30].predicates[0]=Path=/api/exercises/{id}
spring.cloud.gateway.routes[30].predicates[1]=Method=GET

spring.cloud.gateway.routes[31].id=workout-service-get-exercise-by-id-legacy
spring.cloud.gateway.routes[31].uri=lb://workout-service
spring.cloud.gateway.routes[31].predicates[0]=Path=/api/exercises/get/{id}
spring.cloud.gateway.routes[31].predicates[1]=Method=GET

spring.cloud.gateway.routes[32].id=workout-service-create-exercise
spring.cloud.gateway.routes[32].uri=lb://workout-service
spring.cloud.gateway.routes[32].predicates[0]=Path=/api/exercises,/api/exercises/,/api/exercises/create
spring.cloud.gateway.routes[32].predicates[1]=Method=POST

spring.cloud.gateway.routes[33].id=workout-service-update-exercise
spring.cloud.gateway.routes[33].uri=lb://workout-service
spring.cloud.gateway.routes[33].predicates[0]=Path=/api/exercises/{id}
spring.cloud.gateway.routes[33].predicates[1]=Method=PUT

spring.cloud.gateway.routes[34].id=workout-service-delete-exercise
spring.cloud.gateway.routes[34].uri=lb://workout-service
spring.cloud.gateway.routes[34].predicates[0]=Path=/api/exercises/{id}
spring.cloud.gateway.routes[34].predicates[1]=Method=DELETE

spring.cloud.gateway.routes[35].id=workout-service-get-user-progress
spring.cloud.gateway.routes[35].uri=lb://workout-service
spring.cloud.gateway.routes[35].predicates[0]=Path=/api/workouts/progress/user/{userId}
spring.cloud.gateway.routes[35].predicates[1]=Method=GET

spring.cloud.gateway.routes[36].id=workout-service-get-exercise-progress
spring.cloud.gateway.routes[36].uri=lb://workout-service
spring.cloud.gateway.routes[36].predicates[0]=Path=/api/workouts/progress/user/{userId}/exercise/{exerciseId}
spring.cloud.gateway.routes[36].predicates[1]=Method=GET
